/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AppApplicationsRouteImport } from './routes/_app.applications'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppCertificatesRouteImport } from './routes/_app.certificates'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppInspectionsRouteImport } from './routes/_app.inspections'
import { Route as AppNoticesRouteImport } from './routes/_app.notices'
import { Route as AppProvidersRouteImport } from './routes/_app.providers'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSystemRouteImport } from './routes/_app.system'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as BusinessRegisterRouteImport } from './routes/business.register'
import { Route as BusinessSetupRouteImport } from './routes/business.setup'
import { Route as BusinessSignInRouteImport } from './routes/business.sign-in'
import { Route as BusinessVerifyRouteImport } from './routes/business.verify'
import { Route as AppPremisesIndexRouteImport } from './routes/_app.premises.index'
import { Route as AppPremisesPremisesIdRouteImport } from './routes/_app.premises.$premisesId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionsRoute = AppInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessRegisterRoute = BusinessRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessSetupRoute = BusinessSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessSignInRoute = BusinessSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessVerifyRoute = BusinessVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => BusinessRoute,
} as any)
const AppPremisesIndexRoute = AppPremisesIndexRouteImport.update({
  id: '/premises/',
  path: '/premises/',
  getParentRoute: () => AppRoute,
} as any)
const AppPremisesPremisesIdRoute = AppPremisesPremisesIdRouteImport.update({
  id: '/premises/$premisesId',
  path: '/premises/$premisesId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business': typeof BusinessRouteWithChildren
  '/applications': typeof AppApplicationsRoute
  '/audit': typeof AppAuditRoute
  '/certificates': typeof AppCertificatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/inspections': typeof AppInspectionsRoute
  '/notices': typeof AppNoticesRoute
  '/providers': typeof AppProvidersRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/system': typeof AppSystemRoute
  '/users': typeof AppUsersRoute
  '/business/register': typeof BusinessRegisterRoute
  '/business/setup': typeof BusinessSetupRoute
  '/business/sign-in': typeof BusinessSignInRoute
  '/business/verify': typeof BusinessVerifyRoute
  '/business/': typeof BusinessIndexRoute
  '/premises/$premisesId': typeof AppPremisesPremisesIdRoute
  '/premises/': typeof AppPremisesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof AppApplicationsRoute
  '/audit': typeof AppAuditRoute
  '/certificates': typeof AppCertificatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/inspections': typeof AppInspectionsRoute
  '/notices': typeof AppNoticesRoute
  '/providers': typeof AppProvidersRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/system': typeof AppSystemRoute
  '/users': typeof AppUsersRoute
  '/business/register': typeof BusinessRegisterRoute
  '/business/setup': typeof BusinessSetupRoute
  '/business/sign-in': typeof BusinessSignInRoute
  '/business/verify': typeof BusinessVerifyRoute
  '/business': typeof BusinessIndexRoute
  '/premises/$premisesId': typeof AppPremisesPremisesIdRoute
  '/premises': typeof AppPremisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/certificates': typeof AppCertificatesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/inspections': typeof AppInspectionsRoute
  '/_app/notices': typeof AppNoticesRoute
  '/_app/providers': typeof AppProvidersRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/system': typeof AppSystemRoute
  '/_app/users': typeof AppUsersRoute
  '/business/register': typeof BusinessRegisterRoute
  '/business/setup': typeof BusinessSetupRoute
  '/business/sign-in': typeof BusinessSignInRoute
  '/business/verify': typeof BusinessVerifyRoute
  '/business/': typeof BusinessIndexRoute
  '/_app/premises/$premisesId': typeof AppPremisesPremisesIdRoute
  '/_app/premises/': typeof AppPremisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business'
    | '/applications'
    | '/audit'
    | '/certificates'
    | '/dashboard'
    | '/finance'
    | '/inspections'
    | '/notices'
    | '/providers'
    | '/reports'
    | '/settings'
    | '/system'
    | '/users'
    | '/business/register'
    | '/business/setup'
    | '/business/sign-in'
    | '/business/verify'
    | '/business/'
    | '/premises/$premisesId'
    | '/premises/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/audit'
    | '/certificates'
    | '/dashboard'
    | '/finance'
    | '/inspections'
    | '/notices'
    | '/providers'
    | '/reports'
    | '/settings'
    | '/system'
    | '/users'
    | '/business/register'
    | '/business/setup'
    | '/business/sign-in'
    | '/business/verify'
    | '/business'
    | '/premises/$premisesId'
    | '/premises'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/business'
    | '/_app/applications'
    | '/_app/audit'
    | '/_app/certificates'
    | '/_app/dashboard'
    | '/_app/finance'
    | '/_app/inspections'
    | '/_app/notices'
    | '/_app/providers'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/system'
    | '/_app/users'
    | '/business/register'
    | '/business/setup'
    | '/business/sign-in'
    | '/business/verify'
    | '/business/'
    | '/_app/premises/$premisesId'
    | '/_app/premises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BusinessRoute: typeof BusinessRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/certificates': {
      id: '/_app/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspections': {
      id: '/_app/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AppInspectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notices': {
      id: '/_app/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers': {
      id: '/_app/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/register': {
      id: '/business/register'
      path: '/register'
      fullPath: '/business/register'
      preLoaderRoute: typeof BusinessRegisterRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/setup': {
      id: '/business/setup'
      path: '/setup'
      fullPath: '/business/setup'
      preLoaderRoute: typeof BusinessSetupRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/sign-in': {
      id: '/business/sign-in'
      path: '/sign-in'
      fullPath: '/business/sign-in'
      preLoaderRoute: typeof BusinessSignInRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/verify': {
      id: '/business/verify'
      path: '/verify'
      fullPath: '/business/verify'
      preLoaderRoute: typeof BusinessVerifyRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/_app/premises/': {
      id: '/_app/premises/'
      path: '/premises'
      fullPath: '/premises/'
      preLoaderRoute: typeof AppPremisesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/premises/$premisesId': {
      id: '/_app/premises/$premisesId'
      path: '/premises/$premisesId'
      fullPath: '/premises/$premisesId'
      preLoaderRoute: typeof AppPremisesPremisesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppInspectionsRoute: typeof AppInspectionsRoute
  AppNoticesRoute: typeof AppNoticesRoute
  AppProvidersRoute: typeof AppProvidersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSystemRoute: typeof AppSystemRoute
  AppUsersRoute: typeof AppUsersRoute
  AppPremisesPremisesIdRoute: typeof AppPremisesPremisesIdRoute
  AppPremisesIndexRoute: typeof AppPremisesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRoute,
  AppAuditRoute: AppAuditRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppInspectionsRoute: AppInspectionsRoute,
  AppNoticesRoute: AppNoticesRoute,
  AppProvidersRoute: AppProvidersRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSystemRoute: AppSystemRoute,
  AppUsersRoute: AppUsersRoute,
  AppPremisesPremisesIdRoute: AppPremisesPremisesIdRoute,
  AppPremisesIndexRoute: AppPremisesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BusinessRouteChildren {
  BusinessRegisterRoute: typeof BusinessRegisterRoute
  BusinessSetupRoute: typeof BusinessSetupRoute
  BusinessSignInRoute: typeof BusinessSignInRoute
  BusinessVerifyRoute: typeof BusinessVerifyRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessRegisterRoute: BusinessRegisterRoute,
  BusinessSetupRoute: BusinessSetupRoute,
  BusinessSignInRoute: BusinessSignInRoute,
  BusinessVerifyRoute: BusinessVerifyRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BusinessRoute: BusinessRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
