/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as EhoRouteImport } from './routes/eho'
import { Route as MohRouteImport } from './routes/moh'
import { Route as AppApplicationsRouteImport } from './routes/_app.applications'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppCertificatesRouteImport } from './routes/_app.certificates'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppInspectionsRouteImport } from './routes/_app.inspections'
import { Route as AppNoticesRouteImport } from './routes/_app.notices'
import { Route as AppProvidersRouteImport } from './routes/_app.providers'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSystemRouteImport } from './routes/_app.system'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as BusinessPortalRouteImport } from './routes/business._portal'
import { Route as BusinessRegisterRouteImport } from './routes/business.register'
import { Route as BusinessSetupRouteImport } from './routes/business.setup'
import { Route as BusinessSignInRouteImport } from './routes/business.sign-in'
import { Route as BusinessVerifyRouteImport } from './routes/business.verify'
import { Route as EhoIndexRouteImport } from './routes/eho.index'
import { Route as EhoPortalRouteImport } from './routes/eho._portal'
import { Route as EhoSignInRouteImport } from './routes/eho.sign-in'
import { Route as MohIndexRouteImport } from './routes/moh.index'
import { Route as MohHomeRouteImport } from './routes/moh.home'
import { Route as MohSignInRouteImport } from './routes/moh.sign-in'
import { Route as AppPremisesIndexRouteImport } from './routes/_app.premises.index'
import { Route as AppPremisesPremisesIdRouteImport } from './routes/_app.premises.$premisesId'
import { Route as BusinessPortalApplicationsRouteImport } from './routes/business._portal.applications'
import { Route as BusinessPortalCertificatesRouteImport } from './routes/business._portal.certificates'
import { Route as BusinessPortalDashboardRouteImport } from './routes/business._portal.dashboard'
import { Route as BusinessPortalFoodHandlersRouteImport } from './routes/business._portal.food-handlers'
import { Route as BusinessPortalHealthApprovalRouteImport } from './routes/business._portal.health-approval'
import { Route as BusinessPortalInspectionsRouteImport } from './routes/business._portal.inspections'
import { Route as BusinessPortalProfileRouteImport } from './routes/business._portal.profile'
import { Route as BusinessPortalSettingsRouteImport } from './routes/business._portal.settings'
import { Route as EhoPortalFumigationRouteImport } from './routes/eho._portal.fumigation'
import { Route as EhoPortalInspectionsRouteImport } from './routes/eho._portal.inspections'
import { Route as EhoPortalMyWorkRouteImport } from './routes/eho._portal.my-work'
import { Route as EhoPortalPremisesSearchRouteImport } from './routes/eho._portal.premises-search'
import { Route as EhoPortalProfileRouteImport } from './routes/eho._portal.profile'
import { Route as BusinessPortalFitnessApplyRouteImport } from './routes/business._portal.fitness.apply'
import { Route as BusinessPortalFitnessCertificateRouteImport } from './routes/business._portal.fitness.certificate'
import { Route as BusinessPortalFitnessTrackerRouteImport } from './routes/business._portal.fitness.tracker'
import { Route as BusinessPortalFoodHandlerHandlerIdRouteImport } from './routes/business._portal.food-handler.$handlerId'
import { Route as BusinessPortalFoodHandlerNewRouteImport } from './routes/business._portal.food-handler.new'
import { Route as BusinessPortalFumigationApplyRouteImport } from './routes/business._portal.fumigation.apply'
import { Route as BusinessPortalFumigationCertificateRouteImport } from './routes/business._portal.fumigation.certificate'
import { Route as BusinessPortalFumigationTrackerRouteImport } from './routes/business._portal.fumigation.tracker'
import { Route as EhoPortalFumigationJobIdRouteImport } from './routes/eho._portal.fumigation.$jobId'
import { Route as EhoPortalInspectionsInspectionIdRouteImport } from './routes/eho._portal.inspections.$inspectionId'
import { Route as EhoPortalPremisesPremisesIdRouteImport } from './routes/eho._portal.premises.$premisesId'
import { Route as EhoPortalInspectionsInspectionIdChecklistRouteImport } from './routes/eho._portal.inspections.$inspectionId.checklist'
import { Route as EhoPortalInspectionsInspectionIdFindingsRouteImport } from './routes/eho._portal.inspections.$inspectionId.findings'
import { Route as EhoPortalInspectionsInspectionIdFollowUpRouteImport } from './routes/eho._portal.inspections.$inspectionId.follow-up'
import { Route as EhoPortalInspectionsInspectionIdNoticeRouteImport } from './routes/eho._portal.inspections.$inspectionId.notice'
import { Route as EhoPortalInspectionsInspectionIdResultRouteImport } from './routes/eho._portal.inspections.$inspectionId.result'
import { Route as EhoPortalInspectionsInspectionIdReviewRouteImport } from './routes/eho._portal.inspections.$inspectionId.review'
import { Route as EhoPortalInspectionsInspectionIdIssuesItemIdRouteImport } from './routes/eho._portal.inspections.$inspectionId.issues.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const EhoRoute = EhoRouteImport.update({
  id: '/eho',
  path: '/eho',
  getParentRoute: () => rootRouteImport,
} as any)
const MohRoute = MohRouteImport.update({
  id: '/moh',
  path: '/moh',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionsRoute = AppInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessPortalRoute = BusinessPortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessRegisterRoute = BusinessRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessSetupRoute = BusinessSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessSignInRoute = BusinessSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessVerifyRoute = BusinessVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => BusinessRoute,
} as any)
const EhoIndexRoute = EhoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EhoRoute,
} as any)
const EhoPortalRoute = EhoPortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => EhoRoute,
} as any)
const EhoSignInRoute = EhoSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => EhoRoute,
} as any)
const MohIndexRoute = MohIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MohRoute,
} as any)
const MohHomeRoute = MohHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MohRoute,
} as any)
const MohSignInRoute = MohSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => MohRoute,
} as any)
const AppPremisesIndexRoute = AppPremisesIndexRouteImport.update({
  id: '/premises/',
  path: '/premises/',
  getParentRoute: () => AppRoute,
} as any)
const AppPremisesPremisesIdRoute = AppPremisesPremisesIdRouteImport.update({
  id: '/premises/$premisesId',
  path: '/premises/$premisesId',
  getParentRoute: () => AppRoute,
} as any)
const BusinessPortalApplicationsRoute =
  BusinessPortalApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => BusinessPortalRoute,
  } as any)
const BusinessPortalCertificatesRoute =
  BusinessPortalCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => BusinessPortalRoute,
  } as any)
const BusinessPortalDashboardRoute = BusinessPortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BusinessPortalRoute,
} as any)
const BusinessPortalFoodHandlersRoute =
  BusinessPortalFoodHandlersRouteImport.update({
    id: '/food-handlers',
    path: '/food-handlers',
    getParentRoute: () => BusinessPortalRoute,
  } as any)
const BusinessPortalHealthApprovalRoute =
  BusinessPortalHealthApprovalRouteImport.update({
    id: '/health-approval',
    path: '/health-approval',
    getParentRoute: () => BusinessPortalRoute,
  } as any)
const BusinessPortalInspectionsRoute =
  BusinessPortalInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => BusinessPortalRoute,
  } as any)
const BusinessPortalProfileRoute = BusinessPortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BusinessPortalRoute,
} as any)
const BusinessPortalSettingsRoute = BusinessPortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BusinessPortalRoute,
} as any)
const EhoPortalFumigationRoute = EhoPortalFumigationRouteImport.update({
  id: '/fumigation',
  path: '/fumigation',
  getParentRoute: () => EhoPortalRoute,
} as any)
const EhoPortalInspectionsRoute = EhoPortalInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => EhoPortalRoute,
} as any)
const EhoPortalMyWorkRoute = EhoPortalMyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => EhoPortalRoute,
} as any)
const EhoPortalPremisesSearchRoute = EhoPortalPremisesSearchRouteImport.update({
  id: '/premises-search',
  path: '/premises-search',
  getParentRoute: () => EhoPortalRoute,
} as any)
const EhoPortalProfileRoute = EhoPortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EhoPortalRoute,
} as any)
const BusinessPortalFitnessApplyRoute =
  BusinessPortalFitnessApplyRouteImport.update({
    id: '/fitness/apply',
    path: '/fitness/apply',
    getParentRoute: () => BusinessPortalRoute,
  } as any)
const BusinessPortalFitnessCertificateRoute =
  BusinessPortalFitnessCertificateRouteImport.update({
    id: '/fitness/certificate',
    path: '/fitness/certificate',
    getParentRoute: () => BusinessPortalRoute,
  } as any)
const BusinessPortalFitnessTrackerRoute =
  BusinessPortalFitnessTrackerRouteImport.update({
    id: '/fitness/tracker',
    path: '/fitness/tracker',
    getParentRoute: () => BusinessPortalRoute,
  } as any)
const BusinessPortalFoodHandlerHandlerIdRoute =
  BusinessPortalFoodHandlerHandlerIdRouteImport.update({
    id: '/food-handler/$handlerId',
    path: '/food-handler/$handlerId',
    getParentRoute: () => BusinessPortalRoute,
  } as any)
const BusinessPortalFoodHandlerNewRoute =
  BusinessPortalFoodHandlerNewRouteImport.update({
    id: '/food-handler/new',
    path: '/food-handler/new',
    getParentRoute: () => BusinessPortalRoute,
  } as any)
const BusinessPortalFumigationApplyRoute =
  BusinessPortalFumigationApplyRouteImport.update({
    id: '/fumigation/apply',
    path: '/fumigation/apply',
    getParentRoute: () => BusinessPortalRoute,
  } as any)
const BusinessPortalFumigationCertificateRoute =
  BusinessPortalFumigationCertificateRouteImport.update({
    id: '/fumigation/certificate',
    path: '/fumigation/certificate',
    getParentRoute: () => BusinessPortalRoute,
  } as any)
const BusinessPortalFumigationTrackerRoute =
  BusinessPortalFumigationTrackerRouteImport.update({
    id: '/fumigation/tracker',
    path: '/fumigation/tracker',
    getParentRoute: () => BusinessPortalRoute,
  } as any)
const EhoPortalFumigationJobIdRoute =
  EhoPortalFumigationJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => EhoPortalFumigationRoute,
  } as any)
const EhoPortalInspectionsInspectionIdRoute =
  EhoPortalInspectionsInspectionIdRouteImport.update({
    id: '/$inspectionId',
    path: '/$inspectionId',
    getParentRoute: () => EhoPortalInspectionsRoute,
  } as any)
const EhoPortalPremisesPremisesIdRoute =
  EhoPortalPremisesPremisesIdRouteImport.update({
    id: '/premises/$premisesId',
    path: '/premises/$premisesId',
    getParentRoute: () => EhoPortalRoute,
  } as any)
const EhoPortalInspectionsInspectionIdChecklistRoute =
  EhoPortalInspectionsInspectionIdChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => EhoPortalInspectionsInspectionIdRoute,
  } as any)
const EhoPortalInspectionsInspectionIdFindingsRoute =
  EhoPortalInspectionsInspectionIdFindingsRouteImport.update({
    id: '/findings',
    path: '/findings',
    getParentRoute: () => EhoPortalInspectionsInspectionIdRoute,
  } as any)
const EhoPortalInspectionsInspectionIdFollowUpRoute =
  EhoPortalInspectionsInspectionIdFollowUpRouteImport.update({
    id: '/follow-up',
    path: '/follow-up',
    getParentRoute: () => EhoPortalInspectionsInspectionIdRoute,
  } as any)
const EhoPortalInspectionsInspectionIdNoticeRoute =
  EhoPortalInspectionsInspectionIdNoticeRouteImport.update({
    id: '/notice',
    path: '/notice',
    getParentRoute: () => EhoPortalInspectionsInspectionIdRoute,
  } as any)
const EhoPortalInspectionsInspectionIdResultRoute =
  EhoPortalInspectionsInspectionIdResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => EhoPortalInspectionsInspectionIdRoute,
  } as any)
const EhoPortalInspectionsInspectionIdReviewRoute =
  EhoPortalInspectionsInspectionIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => EhoPortalInspectionsInspectionIdRoute,
  } as any)
const EhoPortalInspectionsInspectionIdIssuesItemIdRoute =
  EhoPortalInspectionsInspectionIdIssuesItemIdRouteImport.update({
    id: '/issues/$itemId',
    path: '/issues/$itemId',
    getParentRoute: () => EhoPortalInspectionsInspectionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business': typeof BusinessRouteWithChildren
  '/eho': typeof EhoRouteWithChildren
  '/moh': typeof MohRouteWithChildren
  '/applications': typeof AppApplicationsRoute
  '/audit': typeof AppAuditRoute
  '/certificates': typeof AppCertificatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/inspections': typeof AppInspectionsRoute
  '/notices': typeof AppNoticesRoute
  '/providers': typeof AppProvidersRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/system': typeof AppSystemRoute
  '/users': typeof AppUsersRoute
  '/business/register': typeof BusinessRegisterRoute
  '/business/setup': typeof BusinessSetupRoute
  '/business/sign-in': typeof BusinessSignInRoute
  '/business/verify': typeof BusinessVerifyRoute
  '/eho/sign-in': typeof EhoSignInRoute
  '/moh/home': typeof MohHomeRoute
  '/moh/sign-in': typeof MohSignInRoute
  '/business/': typeof BusinessIndexRoute
  '/eho/': typeof EhoIndexRoute
  '/moh/': typeof MohIndexRoute
  '/premises/$premisesId': typeof AppPremisesPremisesIdRoute
  '/business/applications': typeof BusinessPortalApplicationsRoute
  '/business/certificates': typeof BusinessPortalCertificatesRoute
  '/business/dashboard': typeof BusinessPortalDashboardRoute
  '/business/food-handlers': typeof BusinessPortalFoodHandlersRoute
  '/business/health-approval': typeof BusinessPortalHealthApprovalRoute
  '/business/inspections': typeof BusinessPortalInspectionsRoute
  '/business/profile': typeof BusinessPortalProfileRoute
  '/business/settings': typeof BusinessPortalSettingsRoute
  '/eho/fumigation': typeof EhoPortalFumigationRouteWithChildren
  '/eho/inspections': typeof EhoPortalInspectionsRouteWithChildren
  '/eho/my-work': typeof EhoPortalMyWorkRoute
  '/eho/premises-search': typeof EhoPortalPremisesSearchRoute
  '/eho/profile': typeof EhoPortalProfileRoute
  '/premises/': typeof AppPremisesIndexRoute
  '/business/fitness/apply': typeof BusinessPortalFitnessApplyRoute
  '/business/fitness/certificate': typeof BusinessPortalFitnessCertificateRoute
  '/business/fitness/tracker': typeof BusinessPortalFitnessTrackerRoute
  '/business/food-handler/$handlerId': typeof BusinessPortalFoodHandlerHandlerIdRoute
  '/business/food-handler/new': typeof BusinessPortalFoodHandlerNewRoute
  '/business/fumigation/apply': typeof BusinessPortalFumigationApplyRoute
  '/business/fumigation/certificate': typeof BusinessPortalFumigationCertificateRoute
  '/business/fumigation/tracker': typeof BusinessPortalFumigationTrackerRoute
  '/eho/fumigation/$jobId': typeof EhoPortalFumigationJobIdRoute
  '/eho/inspections/$inspectionId': typeof EhoPortalInspectionsInspectionIdRouteWithChildren
  '/eho/premises/$premisesId': typeof EhoPortalPremisesPremisesIdRoute
  '/eho/inspections/$inspectionId/checklist': typeof EhoPortalInspectionsInspectionIdChecklistRoute
  '/eho/inspections/$inspectionId/findings': typeof EhoPortalInspectionsInspectionIdFindingsRoute
  '/eho/inspections/$inspectionId/follow-up': typeof EhoPortalInspectionsInspectionIdFollowUpRoute
  '/eho/inspections/$inspectionId/notice': typeof EhoPortalInspectionsInspectionIdNoticeRoute
  '/eho/inspections/$inspectionId/result': typeof EhoPortalInspectionsInspectionIdResultRoute
  '/eho/inspections/$inspectionId/review': typeof EhoPortalInspectionsInspectionIdReviewRoute
  '/eho/inspections/$inspectionId/issues/$itemId': typeof EhoPortalInspectionsInspectionIdIssuesItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof AppApplicationsRoute
  '/audit': typeof AppAuditRoute
  '/certificates': typeof AppCertificatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/inspections': typeof AppInspectionsRoute
  '/notices': typeof AppNoticesRoute
  '/providers': typeof AppProvidersRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/system': typeof AppSystemRoute
  '/users': typeof AppUsersRoute
  '/business': typeof BusinessIndexRoute
  '/business/register': typeof BusinessRegisterRoute
  '/business/setup': typeof BusinessSetupRoute
  '/business/sign-in': typeof BusinessSignInRoute
  '/business/verify': typeof BusinessVerifyRoute
  '/eho': typeof EhoIndexRoute
  '/eho/sign-in': typeof EhoSignInRoute
  '/moh/home': typeof MohHomeRoute
  '/moh/sign-in': typeof MohSignInRoute
  '/moh': typeof MohIndexRoute
  '/premises/$premisesId': typeof AppPremisesPremisesIdRoute
  '/business/applications': typeof BusinessPortalApplicationsRoute
  '/business/certificates': typeof BusinessPortalCertificatesRoute
  '/business/dashboard': typeof BusinessPortalDashboardRoute
  '/business/food-handlers': typeof BusinessPortalFoodHandlersRoute
  '/business/health-approval': typeof BusinessPortalHealthApprovalRoute
  '/business/inspections': typeof BusinessPortalInspectionsRoute
  '/business/profile': typeof BusinessPortalProfileRoute
  '/business/settings': typeof BusinessPortalSettingsRoute
  '/eho/fumigation': typeof EhoPortalFumigationRouteWithChildren
  '/eho/inspections': typeof EhoPortalInspectionsRouteWithChildren
  '/eho/my-work': typeof EhoPortalMyWorkRoute
  '/eho/premises-search': typeof EhoPortalPremisesSearchRoute
  '/eho/profile': typeof EhoPortalProfileRoute
  '/premises': typeof AppPremisesIndexRoute
  '/business/fitness/apply': typeof BusinessPortalFitnessApplyRoute
  '/business/fitness/certificate': typeof BusinessPortalFitnessCertificateRoute
  '/business/fitness/tracker': typeof BusinessPortalFitnessTrackerRoute
  '/business/food-handler/$handlerId': typeof BusinessPortalFoodHandlerHandlerIdRoute
  '/business/food-handler/new': typeof BusinessPortalFoodHandlerNewRoute
  '/business/fumigation/apply': typeof BusinessPortalFumigationApplyRoute
  '/business/fumigation/certificate': typeof BusinessPortalFumigationCertificateRoute
  '/business/fumigation/tracker': typeof BusinessPortalFumigationTrackerRoute
  '/eho/fumigation/$jobId': typeof EhoPortalFumigationJobIdRoute
  '/eho/inspections/$inspectionId': typeof EhoPortalInspectionsInspectionIdRouteWithChildren
  '/eho/premises/$premisesId': typeof EhoPortalPremisesPremisesIdRoute
  '/eho/inspections/$inspectionId/checklist': typeof EhoPortalInspectionsInspectionIdChecklistRoute
  '/eho/inspections/$inspectionId/findings': typeof EhoPortalInspectionsInspectionIdFindingsRoute
  '/eho/inspections/$inspectionId/follow-up': typeof EhoPortalInspectionsInspectionIdFollowUpRoute
  '/eho/inspections/$inspectionId/notice': typeof EhoPortalInspectionsInspectionIdNoticeRoute
  '/eho/inspections/$inspectionId/result': typeof EhoPortalInspectionsInspectionIdResultRoute
  '/eho/inspections/$inspectionId/review': typeof EhoPortalInspectionsInspectionIdReviewRoute
  '/eho/inspections/$inspectionId/issues/$itemId': typeof EhoPortalInspectionsInspectionIdIssuesItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/eho': typeof EhoRouteWithChildren
  '/moh': typeof MohRouteWithChildren
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/certificates': typeof AppCertificatesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/inspections': typeof AppInspectionsRoute
  '/_app/notices': typeof AppNoticesRoute
  '/_app/providers': typeof AppProvidersRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/system': typeof AppSystemRoute
  '/_app/users': typeof AppUsersRoute
  '/business/_portal': typeof BusinessPortalRouteWithChildren
  '/business/register': typeof BusinessRegisterRoute
  '/business/setup': typeof BusinessSetupRoute
  '/business/sign-in': typeof BusinessSignInRoute
  '/business/verify': typeof BusinessVerifyRoute
  '/eho/_portal': typeof EhoPortalRouteWithChildren
  '/eho/sign-in': typeof EhoSignInRoute
  '/moh/home': typeof MohHomeRoute
  '/moh/sign-in': typeof MohSignInRoute
  '/business/': typeof BusinessIndexRoute
  '/eho/': typeof EhoIndexRoute
  '/moh/': typeof MohIndexRoute
  '/_app/premises/$premisesId': typeof AppPremisesPremisesIdRoute
  '/business/_portal/applications': typeof BusinessPortalApplicationsRoute
  '/business/_portal/certificates': typeof BusinessPortalCertificatesRoute
  '/business/_portal/dashboard': typeof BusinessPortalDashboardRoute
  '/business/_portal/food-handlers': typeof BusinessPortalFoodHandlersRoute
  '/business/_portal/health-approval': typeof BusinessPortalHealthApprovalRoute
  '/business/_portal/inspections': typeof BusinessPortalInspectionsRoute
  '/business/_portal/profile': typeof BusinessPortalProfileRoute
  '/business/_portal/settings': typeof BusinessPortalSettingsRoute
  '/eho/_portal/fumigation': typeof EhoPortalFumigationRouteWithChildren
  '/eho/_portal/inspections': typeof EhoPortalInspectionsRouteWithChildren
  '/eho/_portal/my-work': typeof EhoPortalMyWorkRoute
  '/eho/_portal/premises-search': typeof EhoPortalPremisesSearchRoute
  '/eho/_portal/profile': typeof EhoPortalProfileRoute
  '/_app/premises/': typeof AppPremisesIndexRoute
  '/business/_portal/fitness/apply': typeof BusinessPortalFitnessApplyRoute
  '/business/_portal/fitness/certificate': typeof BusinessPortalFitnessCertificateRoute
  '/business/_portal/fitness/tracker': typeof BusinessPortalFitnessTrackerRoute
  '/business/_portal/food-handler/$handlerId': typeof BusinessPortalFoodHandlerHandlerIdRoute
  '/business/_portal/food-handler/new': typeof BusinessPortalFoodHandlerNewRoute
  '/business/_portal/fumigation/apply': typeof BusinessPortalFumigationApplyRoute
  '/business/_portal/fumigation/certificate': typeof BusinessPortalFumigationCertificateRoute
  '/business/_portal/fumigation/tracker': typeof BusinessPortalFumigationTrackerRoute
  '/eho/_portal/fumigation/$jobId': typeof EhoPortalFumigationJobIdRoute
  '/eho/_portal/inspections/$inspectionId': typeof EhoPortalInspectionsInspectionIdRouteWithChildren
  '/eho/_portal/premises/$premisesId': typeof EhoPortalPremisesPremisesIdRoute
  '/eho/_portal/inspections/$inspectionId/checklist': typeof EhoPortalInspectionsInspectionIdChecklistRoute
  '/eho/_portal/inspections/$inspectionId/findings': typeof EhoPortalInspectionsInspectionIdFindingsRoute
  '/eho/_portal/inspections/$inspectionId/follow-up': typeof EhoPortalInspectionsInspectionIdFollowUpRoute
  '/eho/_portal/inspections/$inspectionId/notice': typeof EhoPortalInspectionsInspectionIdNoticeRoute
  '/eho/_portal/inspections/$inspectionId/result': typeof EhoPortalInspectionsInspectionIdResultRoute
  '/eho/_portal/inspections/$inspectionId/review': typeof EhoPortalInspectionsInspectionIdReviewRoute
  '/eho/_portal/inspections/$inspectionId/issues/$itemId': typeof EhoPortalInspectionsInspectionIdIssuesItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business'
    | '/eho'
    | '/moh'
    | '/applications'
    | '/audit'
    | '/certificates'
    | '/dashboard'
    | '/finance'
    | '/inspections'
    | '/notices'
    | '/providers'
    | '/reports'
    | '/settings'
    | '/system'
    | '/users'
    | '/business/register'
    | '/business/setup'
    | '/business/sign-in'
    | '/business/verify'
    | '/eho/sign-in'
    | '/moh/home'
    | '/moh/sign-in'
    | '/business/'
    | '/eho/'
    | '/moh/'
    | '/premises/$premisesId'
    | '/business/applications'
    | '/business/certificates'
    | '/business/dashboard'
    | '/business/food-handlers'
    | '/business/health-approval'
    | '/business/inspections'
    | '/business/profile'
    | '/business/settings'
    | '/eho/fumigation'
    | '/eho/inspections'
    | '/eho/my-work'
    | '/eho/premises-search'
    | '/eho/profile'
    | '/premises/'
    | '/business/fitness/apply'
    | '/business/fitness/certificate'
    | '/business/fitness/tracker'
    | '/business/food-handler/$handlerId'
    | '/business/food-handler/new'
    | '/business/fumigation/apply'
    | '/business/fumigation/certificate'
    | '/business/fumigation/tracker'
    | '/eho/fumigation/$jobId'
    | '/eho/inspections/$inspectionId'
    | '/eho/premises/$premisesId'
    | '/eho/inspections/$inspectionId/checklist'
    | '/eho/inspections/$inspectionId/findings'
    | '/eho/inspections/$inspectionId/follow-up'
    | '/eho/inspections/$inspectionId/notice'
    | '/eho/inspections/$inspectionId/result'
    | '/eho/inspections/$inspectionId/review'
    | '/eho/inspections/$inspectionId/issues/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/audit'
    | '/certificates'
    | '/dashboard'
    | '/finance'
    | '/inspections'
    | '/notices'
    | '/providers'
    | '/reports'
    | '/settings'
    | '/system'
    | '/users'
    | '/business'
    | '/business/register'
    | '/business/setup'
    | '/business/sign-in'
    | '/business/verify'
    | '/eho'
    | '/eho/sign-in'
    | '/moh/home'
    | '/moh/sign-in'
    | '/moh'
    | '/premises/$premisesId'
    | '/business/applications'
    | '/business/certificates'
    | '/business/dashboard'
    | '/business/food-handlers'
    | '/business/health-approval'
    | '/business/inspections'
    | '/business/profile'
    | '/business/settings'
    | '/eho/fumigation'
    | '/eho/inspections'
    | '/eho/my-work'
    | '/eho/premises-search'
    | '/eho/profile'
    | '/premises'
    | '/business/fitness/apply'
    | '/business/fitness/certificate'
    | '/business/fitness/tracker'
    | '/business/food-handler/$handlerId'
    | '/business/food-handler/new'
    | '/business/fumigation/apply'
    | '/business/fumigation/certificate'
    | '/business/fumigation/tracker'
    | '/eho/fumigation/$jobId'
    | '/eho/inspections/$inspectionId'
    | '/eho/premises/$premisesId'
    | '/eho/inspections/$inspectionId/checklist'
    | '/eho/inspections/$inspectionId/findings'
    | '/eho/inspections/$inspectionId/follow-up'
    | '/eho/inspections/$inspectionId/notice'
    | '/eho/inspections/$inspectionId/result'
    | '/eho/inspections/$inspectionId/review'
    | '/eho/inspections/$inspectionId/issues/$itemId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/business'
    | '/eho'
    | '/moh'
    | '/_app/applications'
    | '/_app/audit'
    | '/_app/certificates'
    | '/_app/dashboard'
    | '/_app/finance'
    | '/_app/inspections'
    | '/_app/notices'
    | '/_app/providers'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/system'
    | '/_app/users'
    | '/business/_portal'
    | '/business/register'
    | '/business/setup'
    | '/business/sign-in'
    | '/business/verify'
    | '/eho/_portal'
    | '/eho/sign-in'
    | '/moh/home'
    | '/moh/sign-in'
    | '/business/'
    | '/eho/'
    | '/moh/'
    | '/_app/premises/$premisesId'
    | '/business/_portal/applications'
    | '/business/_portal/certificates'
    | '/business/_portal/dashboard'
    | '/business/_portal/food-handlers'
    | '/business/_portal/health-approval'
    | '/business/_portal/inspections'
    | '/business/_portal/profile'
    | '/business/_portal/settings'
    | '/eho/_portal/fumigation'
    | '/eho/_portal/inspections'
    | '/eho/_portal/my-work'
    | '/eho/_portal/premises-search'
    | '/eho/_portal/profile'
    | '/_app/premises/'
    | '/business/_portal/fitness/apply'
    | '/business/_portal/fitness/certificate'
    | '/business/_portal/fitness/tracker'
    | '/business/_portal/food-handler/$handlerId'
    | '/business/_portal/food-handler/new'
    | '/business/_portal/fumigation/apply'
    | '/business/_portal/fumigation/certificate'
    | '/business/_portal/fumigation/tracker'
    | '/eho/_portal/fumigation/$jobId'
    | '/eho/_portal/inspections/$inspectionId'
    | '/eho/_portal/premises/$premisesId'
    | '/eho/_portal/inspections/$inspectionId/checklist'
    | '/eho/_portal/inspections/$inspectionId/findings'
    | '/eho/_portal/inspections/$inspectionId/follow-up'
    | '/eho/_portal/inspections/$inspectionId/notice'
    | '/eho/_portal/inspections/$inspectionId/result'
    | '/eho/_portal/inspections/$inspectionId/review'
    | '/eho/_portal/inspections/$inspectionId/issues/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BusinessRoute: typeof BusinessRouteWithChildren
  EhoRoute: typeof EhoRouteWithChildren
  MohRoute: typeof MohRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eho': {
      id: '/eho'
      path: '/eho'
      fullPath: '/eho'
      preLoaderRoute: typeof EhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moh': {
      id: '/moh'
      path: '/moh'
      fullPath: '/moh'
      preLoaderRoute: typeof MohRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/certificates': {
      id: '/_app/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspections': {
      id: '/_app/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AppInspectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notices': {
      id: '/_app/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers': {
      id: '/_app/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/_portal': {
      id: '/business/_portal'
      path: ''
      fullPath: '/business'
      preLoaderRoute: typeof BusinessPortalRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/register': {
      id: '/business/register'
      path: '/register'
      fullPath: '/business/register'
      preLoaderRoute: typeof BusinessRegisterRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/setup': {
      id: '/business/setup'
      path: '/setup'
      fullPath: '/business/setup'
      preLoaderRoute: typeof BusinessSetupRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/sign-in': {
      id: '/business/sign-in'
      path: '/sign-in'
      fullPath: '/business/sign-in'
      preLoaderRoute: typeof BusinessSignInRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/verify': {
      id: '/business/verify'
      path: '/verify'
      fullPath: '/business/verify'
      preLoaderRoute: typeof BusinessVerifyRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/eho/': {
      id: '/eho/'
      path: '/'
      fullPath: '/eho/'
      preLoaderRoute: typeof EhoIndexRouteImport
      parentRoute: typeof EhoRoute
    }
    '/eho/_portal': {
      id: '/eho/_portal'
      path: ''
      fullPath: '/eho'
      preLoaderRoute: typeof EhoPortalRouteImport
      parentRoute: typeof EhoRoute
    }
    '/eho/sign-in': {
      id: '/eho/sign-in'
      path: '/sign-in'
      fullPath: '/eho/sign-in'
      preLoaderRoute: typeof EhoSignInRouteImport
      parentRoute: typeof EhoRoute
    }
    '/moh/': {
      id: '/moh/'
      path: '/'
      fullPath: '/moh/'
      preLoaderRoute: typeof MohIndexRouteImport
      parentRoute: typeof MohRoute
    }
    '/moh/home': {
      id: '/moh/home'
      path: '/home'
      fullPath: '/moh/home'
      preLoaderRoute: typeof MohHomeRouteImport
      parentRoute: typeof MohRoute
    }
    '/moh/sign-in': {
      id: '/moh/sign-in'
      path: '/sign-in'
      fullPath: '/moh/sign-in'
      preLoaderRoute: typeof MohSignInRouteImport
      parentRoute: typeof MohRoute
    }
    '/_app/premises/': {
      id: '/_app/premises/'
      path: '/premises'
      fullPath: '/premises/'
      preLoaderRoute: typeof AppPremisesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/premises/$premisesId': {
      id: '/_app/premises/$premisesId'
      path: '/premises/$premisesId'
      fullPath: '/premises/$premisesId'
      preLoaderRoute: typeof AppPremisesPremisesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/business/_portal/applications': {
      id: '/business/_portal/applications'
      path: '/applications'
      fullPath: '/business/applications'
      preLoaderRoute: typeof BusinessPortalApplicationsRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/business/_portal/certificates': {
      id: '/business/_portal/certificates'
      path: '/certificates'
      fullPath: '/business/certificates'
      preLoaderRoute: typeof BusinessPortalCertificatesRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/business/_portal/dashboard': {
      id: '/business/_portal/dashboard'
      path: '/dashboard'
      fullPath: '/business/dashboard'
      preLoaderRoute: typeof BusinessPortalDashboardRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/business/_portal/food-handlers': {
      id: '/business/_portal/food-handlers'
      path: '/food-handlers'
      fullPath: '/business/food-handlers'
      preLoaderRoute: typeof BusinessPortalFoodHandlersRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/business/_portal/health-approval': {
      id: '/business/_portal/health-approval'
      path: '/health-approval'
      fullPath: '/business/health-approval'
      preLoaderRoute: typeof BusinessPortalHealthApprovalRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/business/_portal/inspections': {
      id: '/business/_portal/inspections'
      path: '/inspections'
      fullPath: '/business/inspections'
      preLoaderRoute: typeof BusinessPortalInspectionsRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/business/_portal/profile': {
      id: '/business/_portal/profile'
      path: '/profile'
      fullPath: '/business/profile'
      preLoaderRoute: typeof BusinessPortalProfileRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/business/_portal/settings': {
      id: '/business/_portal/settings'
      path: '/settings'
      fullPath: '/business/settings'
      preLoaderRoute: typeof BusinessPortalSettingsRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/eho/_portal/fumigation': {
      id: '/eho/_portal/fumigation'
      path: '/fumigation'
      fullPath: '/eho/fumigation'
      preLoaderRoute: typeof EhoPortalFumigationRouteImport
      parentRoute: typeof EhoPortalRoute
    }
    '/eho/_portal/inspections': {
      id: '/eho/_portal/inspections'
      path: '/inspections'
      fullPath: '/eho/inspections'
      preLoaderRoute: typeof EhoPortalInspectionsRouteImport
      parentRoute: typeof EhoPortalRoute
    }
    '/eho/_portal/my-work': {
      id: '/eho/_portal/my-work'
      path: '/my-work'
      fullPath: '/eho/my-work'
      preLoaderRoute: typeof EhoPortalMyWorkRouteImport
      parentRoute: typeof EhoPortalRoute
    }
    '/eho/_portal/premises-search': {
      id: '/eho/_portal/premises-search'
      path: '/premises-search'
      fullPath: '/eho/premises-search'
      preLoaderRoute: typeof EhoPortalPremisesSearchRouteImport
      parentRoute: typeof EhoPortalRoute
    }
    '/eho/_portal/profile': {
      id: '/eho/_portal/profile'
      path: '/profile'
      fullPath: '/eho/profile'
      preLoaderRoute: typeof EhoPortalProfileRouteImport
      parentRoute: typeof EhoPortalRoute
    }
    '/business/_portal/fitness/apply': {
      id: '/business/_portal/fitness/apply'
      path: '/fitness/apply'
      fullPath: '/business/fitness/apply'
      preLoaderRoute: typeof BusinessPortalFitnessApplyRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/business/_portal/fitness/certificate': {
      id: '/business/_portal/fitness/certificate'
      path: '/fitness/certificate'
      fullPath: '/business/fitness/certificate'
      preLoaderRoute: typeof BusinessPortalFitnessCertificateRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/business/_portal/fitness/tracker': {
      id: '/business/_portal/fitness/tracker'
      path: '/fitness/tracker'
      fullPath: '/business/fitness/tracker'
      preLoaderRoute: typeof BusinessPortalFitnessTrackerRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/business/_portal/food-handler/$handlerId': {
      id: '/business/_portal/food-handler/$handlerId'
      path: '/food-handler/$handlerId'
      fullPath: '/business/food-handler/$handlerId'
      preLoaderRoute: typeof BusinessPortalFoodHandlerHandlerIdRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/business/_portal/food-handler/new': {
      id: '/business/_portal/food-handler/new'
      path: '/food-handler/new'
      fullPath: '/business/food-handler/new'
      preLoaderRoute: typeof BusinessPortalFoodHandlerNewRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/business/_portal/fumigation/apply': {
      id: '/business/_portal/fumigation/apply'
      path: '/fumigation/apply'
      fullPath: '/business/fumigation/apply'
      preLoaderRoute: typeof BusinessPortalFumigationApplyRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/business/_portal/fumigation/certificate': {
      id: '/business/_portal/fumigation/certificate'
      path: '/fumigation/certificate'
      fullPath: '/business/fumigation/certificate'
      preLoaderRoute: typeof BusinessPortalFumigationCertificateRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/business/_portal/fumigation/tracker': {
      id: '/business/_portal/fumigation/tracker'
      path: '/fumigation/tracker'
      fullPath: '/business/fumigation/tracker'
      preLoaderRoute: typeof BusinessPortalFumigationTrackerRouteImport
      parentRoute: typeof BusinessPortalRoute
    }
    '/eho/_portal/fumigation/$jobId': {
      id: '/eho/_portal/fumigation/$jobId'
      path: '/$jobId'
      fullPath: '/eho/fumigation/$jobId'
      preLoaderRoute: typeof EhoPortalFumigationJobIdRouteImport
      parentRoute: typeof EhoPortalFumigationRoute
    }
    '/eho/_portal/inspections/$inspectionId': {
      id: '/eho/_portal/inspections/$inspectionId'
      path: '/$inspectionId'
      fullPath: '/eho/inspections/$inspectionId'
      preLoaderRoute: typeof EhoPortalInspectionsInspectionIdRouteImport
      parentRoute: typeof EhoPortalInspectionsRoute
    }
    '/eho/_portal/premises/$premisesId': {
      id: '/eho/_portal/premises/$premisesId'
      path: '/premises/$premisesId'
      fullPath: '/eho/premises/$premisesId'
      preLoaderRoute: typeof EhoPortalPremisesPremisesIdRouteImport
      parentRoute: typeof EhoPortalRoute
    }
    '/eho/_portal/inspections/$inspectionId/checklist': {
      id: '/eho/_portal/inspections/$inspectionId/checklist'
      path: '/checklist'
      fullPath: '/eho/inspections/$inspectionId/checklist'
      preLoaderRoute: typeof EhoPortalInspectionsInspectionIdChecklistRouteImport
      parentRoute: typeof EhoPortalInspectionsInspectionIdRoute
    }
    '/eho/_portal/inspections/$inspectionId/findings': {
      id: '/eho/_portal/inspections/$inspectionId/findings'
      path: '/findings'
      fullPath: '/eho/inspections/$inspectionId/findings'
      preLoaderRoute: typeof EhoPortalInspectionsInspectionIdFindingsRouteImport
      parentRoute: typeof EhoPortalInspectionsInspectionIdRoute
    }
    '/eho/_portal/inspections/$inspectionId/follow-up': {
      id: '/eho/_portal/inspections/$inspectionId/follow-up'
      path: '/follow-up'
      fullPath: '/eho/inspections/$inspectionId/follow-up'
      preLoaderRoute: typeof EhoPortalInspectionsInspectionIdFollowUpRouteImport
      parentRoute: typeof EhoPortalInspectionsInspectionIdRoute
    }
    '/eho/_portal/inspections/$inspectionId/notice': {
      id: '/eho/_portal/inspections/$inspectionId/notice'
      path: '/notice'
      fullPath: '/eho/inspections/$inspectionId/notice'
      preLoaderRoute: typeof EhoPortalInspectionsInspectionIdNoticeRouteImport
      parentRoute: typeof EhoPortalInspectionsInspectionIdRoute
    }
    '/eho/_portal/inspections/$inspectionId/result': {
      id: '/eho/_portal/inspections/$inspectionId/result'
      path: '/result'
      fullPath: '/eho/inspections/$inspectionId/result'
      preLoaderRoute: typeof EhoPortalInspectionsInspectionIdResultRouteImport
      parentRoute: typeof EhoPortalInspectionsInspectionIdRoute
    }
    '/eho/_portal/inspections/$inspectionId/review': {
      id: '/eho/_portal/inspections/$inspectionId/review'
      path: '/review'
      fullPath: '/eho/inspections/$inspectionId/review'
      preLoaderRoute: typeof EhoPortalInspectionsInspectionIdReviewRouteImport
      parentRoute: typeof EhoPortalInspectionsInspectionIdRoute
    }
    '/eho/_portal/inspections/$inspectionId/issues/$itemId': {
      id: '/eho/_portal/inspections/$inspectionId/issues/$itemId'
      path: '/issues/$itemId'
      fullPath: '/eho/inspections/$inspectionId/issues/$itemId'
      preLoaderRoute: typeof EhoPortalInspectionsInspectionIdIssuesItemIdRouteImport
      parentRoute: typeof EhoPortalInspectionsInspectionIdRoute
    }
  }
}

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppInspectionsRoute: typeof AppInspectionsRoute
  AppNoticesRoute: typeof AppNoticesRoute
  AppProvidersRoute: typeof AppProvidersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSystemRoute: typeof AppSystemRoute
  AppUsersRoute: typeof AppUsersRoute
  AppPremisesPremisesIdRoute: typeof AppPremisesPremisesIdRoute
  AppPremisesIndexRoute: typeof AppPremisesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRoute,
  AppAuditRoute: AppAuditRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppInspectionsRoute: AppInspectionsRoute,
  AppNoticesRoute: AppNoticesRoute,
  AppProvidersRoute: AppProvidersRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSystemRoute: AppSystemRoute,
  AppUsersRoute: AppUsersRoute,
  AppPremisesPremisesIdRoute: AppPremisesPremisesIdRoute,
  AppPremisesIndexRoute: AppPremisesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BusinessPortalRouteChildren {
  BusinessPortalApplicationsRoute: typeof BusinessPortalApplicationsRoute
  BusinessPortalCertificatesRoute: typeof BusinessPortalCertificatesRoute
  BusinessPortalDashboardRoute: typeof BusinessPortalDashboardRoute
  BusinessPortalFoodHandlersRoute: typeof BusinessPortalFoodHandlersRoute
  BusinessPortalHealthApprovalRoute: typeof BusinessPortalHealthApprovalRoute
  BusinessPortalInspectionsRoute: typeof BusinessPortalInspectionsRoute
  BusinessPortalProfileRoute: typeof BusinessPortalProfileRoute
  BusinessPortalSettingsRoute: typeof BusinessPortalSettingsRoute
  BusinessPortalFitnessApplyRoute: typeof BusinessPortalFitnessApplyRoute
  BusinessPortalFitnessCertificateRoute: typeof BusinessPortalFitnessCertificateRoute
  BusinessPortalFitnessTrackerRoute: typeof BusinessPortalFitnessTrackerRoute
  BusinessPortalFoodHandlerHandlerIdRoute: typeof BusinessPortalFoodHandlerHandlerIdRoute
  BusinessPortalFoodHandlerNewRoute: typeof BusinessPortalFoodHandlerNewRoute
  BusinessPortalFumigationApplyRoute: typeof BusinessPortalFumigationApplyRoute
  BusinessPortalFumigationCertificateRoute: typeof BusinessPortalFumigationCertificateRoute
  BusinessPortalFumigationTrackerRoute: typeof BusinessPortalFumigationTrackerRoute
}

const BusinessPortalRouteChildren: BusinessPortalRouteChildren = {
  BusinessPortalApplicationsRoute: BusinessPortalApplicationsRoute,
  BusinessPortalCertificatesRoute: BusinessPortalCertificatesRoute,
  BusinessPortalDashboardRoute: BusinessPortalDashboardRoute,
  BusinessPortalFoodHandlersRoute: BusinessPortalFoodHandlersRoute,
  BusinessPortalHealthApprovalRoute: BusinessPortalHealthApprovalRoute,
  BusinessPortalInspectionsRoute: BusinessPortalInspectionsRoute,
  BusinessPortalProfileRoute: BusinessPortalProfileRoute,
  BusinessPortalSettingsRoute: BusinessPortalSettingsRoute,
  BusinessPortalFitnessApplyRoute: BusinessPortalFitnessApplyRoute,
  BusinessPortalFitnessCertificateRoute: BusinessPortalFitnessCertificateRoute,
  BusinessPortalFitnessTrackerRoute: BusinessPortalFitnessTrackerRoute,
  BusinessPortalFoodHandlerHandlerIdRoute:
    BusinessPortalFoodHandlerHandlerIdRoute,
  BusinessPortalFoodHandlerNewRoute: BusinessPortalFoodHandlerNewRoute,
  BusinessPortalFumigationApplyRoute: BusinessPortalFumigationApplyRoute,
  BusinessPortalFumigationCertificateRoute:
    BusinessPortalFumigationCertificateRoute,
  BusinessPortalFumigationTrackerRoute: BusinessPortalFumigationTrackerRoute,
}

const BusinessPortalRouteWithChildren = BusinessPortalRoute._addFileChildren(
  BusinessPortalRouteChildren,
)

interface BusinessRouteChildren {
  BusinessPortalRoute: typeof BusinessPortalRouteWithChildren
  BusinessRegisterRoute: typeof BusinessRegisterRoute
  BusinessSetupRoute: typeof BusinessSetupRoute
  BusinessSignInRoute: typeof BusinessSignInRoute
  BusinessVerifyRoute: typeof BusinessVerifyRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessPortalRoute: BusinessPortalRouteWithChildren,
  BusinessRegisterRoute: BusinessRegisterRoute,
  BusinessSetupRoute: BusinessSetupRoute,
  BusinessSignInRoute: BusinessSignInRoute,
  BusinessVerifyRoute: BusinessVerifyRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

interface EhoPortalFumigationRouteChildren {
  EhoPortalFumigationJobIdRoute: typeof EhoPortalFumigationJobIdRoute
}

const EhoPortalFumigationRouteChildren: EhoPortalFumigationRouteChildren = {
  EhoPortalFumigationJobIdRoute: EhoPortalFumigationJobIdRoute,
}

const EhoPortalFumigationRouteWithChildren =
  EhoPortalFumigationRoute._addFileChildren(EhoPortalFumigationRouteChildren)

interface EhoPortalInspectionsInspectionIdRouteChildren {
  EhoPortalInspectionsInspectionIdChecklistRoute: typeof EhoPortalInspectionsInspectionIdChecklistRoute
  EhoPortalInspectionsInspectionIdFindingsRoute: typeof EhoPortalInspectionsInspectionIdFindingsRoute
  EhoPortalInspectionsInspectionIdFollowUpRoute: typeof EhoPortalInspectionsInspectionIdFollowUpRoute
  EhoPortalInspectionsInspectionIdNoticeRoute: typeof EhoPortalInspectionsInspectionIdNoticeRoute
  EhoPortalInspectionsInspectionIdResultRoute: typeof EhoPortalInspectionsInspectionIdResultRoute
  EhoPortalInspectionsInspectionIdReviewRoute: typeof EhoPortalInspectionsInspectionIdReviewRoute
  EhoPortalInspectionsInspectionIdIssuesItemIdRoute: typeof EhoPortalInspectionsInspectionIdIssuesItemIdRoute
}

const EhoPortalInspectionsInspectionIdRouteChildren: EhoPortalInspectionsInspectionIdRouteChildren =
  {
    EhoPortalInspectionsInspectionIdChecklistRoute:
      EhoPortalInspectionsInspectionIdChecklistRoute,
    EhoPortalInspectionsInspectionIdFindingsRoute:
      EhoPortalInspectionsInspectionIdFindingsRoute,
    EhoPortalInspectionsInspectionIdFollowUpRoute:
      EhoPortalInspectionsInspectionIdFollowUpRoute,
    EhoPortalInspectionsInspectionIdNoticeRoute:
      EhoPortalInspectionsInspectionIdNoticeRoute,
    EhoPortalInspectionsInspectionIdResultRoute:
      EhoPortalInspectionsInspectionIdResultRoute,
    EhoPortalInspectionsInspectionIdReviewRoute:
      EhoPortalInspectionsInspectionIdReviewRoute,
    EhoPortalInspectionsInspectionIdIssuesItemIdRoute:
      EhoPortalInspectionsInspectionIdIssuesItemIdRoute,
  }

const EhoPortalInspectionsInspectionIdRouteWithChildren =
  EhoPortalInspectionsInspectionIdRoute._addFileChildren(
    EhoPortalInspectionsInspectionIdRouteChildren,
  )

interface EhoPortalInspectionsRouteChildren {
  EhoPortalInspectionsInspectionIdRoute: typeof EhoPortalInspectionsInspectionIdRouteWithChildren
}

const EhoPortalInspectionsRouteChildren: EhoPortalInspectionsRouteChildren = {
  EhoPortalInspectionsInspectionIdRoute:
    EhoPortalInspectionsInspectionIdRouteWithChildren,
}

const EhoPortalInspectionsRouteWithChildren =
  EhoPortalInspectionsRoute._addFileChildren(EhoPortalInspectionsRouteChildren)

interface EhoPortalRouteChildren {
  EhoPortalFumigationRoute: typeof EhoPortalFumigationRouteWithChildren
  EhoPortalInspectionsRoute: typeof EhoPortalInspectionsRouteWithChildren
  EhoPortalMyWorkRoute: typeof EhoPortalMyWorkRoute
  EhoPortalPremisesSearchRoute: typeof EhoPortalPremisesSearchRoute
  EhoPortalProfileRoute: typeof EhoPortalProfileRoute
  EhoPortalPremisesPremisesIdRoute: typeof EhoPortalPremisesPremisesIdRoute
}

const EhoPortalRouteChildren: EhoPortalRouteChildren = {
  EhoPortalFumigationRoute: EhoPortalFumigationRouteWithChildren,
  EhoPortalInspectionsRoute: EhoPortalInspectionsRouteWithChildren,
  EhoPortalMyWorkRoute: EhoPortalMyWorkRoute,
  EhoPortalPremisesSearchRoute: EhoPortalPremisesSearchRoute,
  EhoPortalProfileRoute: EhoPortalProfileRoute,
  EhoPortalPremisesPremisesIdRoute: EhoPortalPremisesPremisesIdRoute,
}

const EhoPortalRouteWithChildren = EhoPortalRoute._addFileChildren(
  EhoPortalRouteChildren,
)

interface EhoRouteChildren {
  EhoPortalRoute: typeof EhoPortalRouteWithChildren
  EhoSignInRoute: typeof EhoSignInRoute
  EhoIndexRoute: typeof EhoIndexRoute
}

const EhoRouteChildren: EhoRouteChildren = {
  EhoPortalRoute: EhoPortalRouteWithChildren,
  EhoSignInRoute: EhoSignInRoute,
  EhoIndexRoute: EhoIndexRoute,
}

const EhoRouteWithChildren = EhoRoute._addFileChildren(EhoRouteChildren)

interface MohRouteChildren {
  MohHomeRoute: typeof MohHomeRoute
  MohSignInRoute: typeof MohSignInRoute
  MohIndexRoute: typeof MohIndexRoute
}

const MohRouteChildren: MohRouteChildren = {
  MohHomeRoute: MohHomeRoute,
  MohSignInRoute: MohSignInRoute,
  MohIndexRoute: MohIndexRoute,
}

const MohRouteWithChildren = MohRoute._addFileChildren(MohRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BusinessRoute: BusinessRouteWithChildren,
  EhoRoute: EhoRouteWithChildren,
  MohRoute: MohRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
